### ISSUE TITLE
GreasyFork链接已被举报下架

### ISSUE THREAD

**Issue by suiyuanla** [WiresawBlade/Tieba-Remix#11]
GreasyFork链接已被举报下架

链接：https://greasyfork.org/zh-CN/scripts/460113-tieba-remix
访问结果 ：请求的脚本已因[该举报](https://greasyfork.org/zh-CN/reports/53338)而被删除。不过，这里有一些相关的脚本。

**Comment by WiresawBlade** [comment]
前段时间我也发现了，我一般会单独给 gf 上传一个没压缩的版本，最后一次上传的时候可能给忘了，那个版本又在上面挂了很久所以被下了。这段时间实在是太忙了，看到了也没法第一时间处理，等过年放假吧

**Comment by WiresawBlade** [comment]
已恢复 https://greasyfork.org/zh-CN/scripts/486367
