### ISSUE TITLE
能否添加一个新老版本看帖页面的切换功能

### ISSUE THREAD

**Issue by huhuhahi** [WiresawBlade/Tieba-Remix#17]
目前新版本的界面更新后用着不太舒服有点后悔，想用回老版本的，gf上被举报下架，能否提供一个切换新老版本页面的选项，或者同时提供beta版和老版下载

**Comment by WiresawBlade** [comment]
两个版本共存可能是 gf 上的脚本会强制修改 namespace 的锅；
刚刚推了新版，新版页面都可以自己关了
