### ISSUE TITLE
打开链接问题

### ISSUE THREAD

**Issue by hao1196561270** [WiresawBlade/Tieba-Remix#2]
![1](https://github.com/WiresawBlade/Tieba-Remix/assets/129362575/d783b639-d399-4bb8-838f-e9e561658f62)
![2](https://github.com/WiresawBlade/Tieba-Remix/assets/129362575/3301d66c-0e29-4091-a29b-6bdc82e8a3ff)
如图所示，开启插件后无法显示链接跳转窗口

**Comment by hao1196561270** [comment]
不用插件时是可以的

**Comment by WiresawBlade** [comment]
问题已修复，将在下个版本合并。如有其他问题欢迎继续追踪

**Comment by hao1196561270** [comment]
![image](https://github.com/WiresawBlade/Tieba-Remix/assets/129362575/829271cb-2670-4db7-babe-8435fb1b6f90)
https://tieba.baidu.com/ 我的收藏以及修改点击无反应

**Comment by WiresawBlade** [comment]
> ![image](https://user-images.githubusercontent.com/129362575/238128882-829271cb-2670-4db7-babe-8435fb1b6f90.png) https://tieba.baidu.com/ 我的收藏以及修改点击无反应

其实没有反应才是正常的，因为压根就没有实装👉👈
工程量太大了，个人时间也比较有限，功能没办法一次性测试完，只能分批推送。下个版本会先增加实验性功能的开关，现阶段想访问旧版主页只能访问 [`http://jump2.bdimg.com/`](http://jump2.bdimg.com/)  ，不过还是不太推荐这么做

**Comment by WiresawBlade** [comment]
> ![image](https://user-images.githubusercontent.com/129362575/238128882-829271cb-2670-4db7-babe-8435fb1b6f90.png) https://tieba.baidu.com/ 我的收藏以及修改点击无反应

其实没有反应才是正常的，因为压根就没有实装👉👈
工程量太大了，个人时间也比较有限，功能没办法一次性测试完，只能分批推送。下个版本会先增加实验性功能的开关，现阶段想访问原版主页只能访问 [`http://jump2.bdimg.com/`](http://jump2.bdimg.com/)  ，不过还是不太推荐这么做
  
> 注：刚才刚推送了新版，因此上文提到的所谓“下个版本”还不知道要什么时候

**Comment by hao1196561270** [comment]
> > ![image](https://user-images.githubusercontent.com/129362575/238128882-829271cb-2670-4db7-babe-8435fb1b6f90.png) https://tieba.baidu.com/ 我的收藏以及修改点击无反应
> 
> 其实没有反应才是正常的，因为压根就没有实装👉👈 工程量太大了，个人时间也比较有限，功能没办法一次性测试完，只能分批推送。下个版本会先增加实验性功能的开关，现阶段想访问原版主页只能访问 [`http://jump2.bdimg.com/`](http://jump2.bdimg.com/) ，不过还是不太推荐这么做
> 
> > 注：刚才刚推送了新版，因此上文提到的所谓“下个版本”还不知道要什么时候

好的 理解 辛苦
