### ISSUE TITLE
可以增加一个字体模块吗

### ISSUE THREAD

**Issue by naseaoi** [WiresawBlade/Tieba-Remix#21]
现在的字体应该不是默认的系统字体吧，看久了感觉有点难受，能增加一个恢复系统默认字体的模块嘛

**Comment by W7LL-E** [comment]
+1

**Comment by WiresawBlade** [comment]
忘给这个功能加设置组件了。。。这个版本拖了实在太久，很多细枝末节的地方都想不起来了

**Comment by WiresawBlade** [comment]
功能已正式支持，会合并到下个版本。如果现在就很需要可以直接在 `/build/tieba-remix.user.js` 下载

![image](https://github.com/WiresawBlade/Tieba-Remix/assets/62379610/9531a95d-49fb-4943-bda7-184e9685dcce)

**Comment by naseaoi** [comment]
> 功能已正式支持，会合并到下个版本。如果现在就很需要可以直接在 `/build/tieba-remix.user.js` 下载
> 
> ![image](https://private-user-images.githubusercontent.com/62379610/302038613-9531a95d-49fb-4943-bda7-184e9685dcce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1Mjk4MjQsIm5iZiI6MTcwNzUyOTUyNCwicGF0aCI6Ii82MjM3OTYxMC8zMDIwMzg2MTMtOTUzMWE5NWQtNDlmYi00OTQzLWJkYTctMTg0ZTk2ODVkY2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDAxNDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MGZhM2M2OTU1OThmNmQxODg2Nzc4MmRiY2U3ZDY0ZjYwM2VkNTNkNzgzZjNhYzYyMWI0OWE0ZWIwOWMxMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ONCR3CiXHLupY9XeoNPa8KfewP1wfn_qft3TujusZMI)

大佬牛逼，新年快乐！
