### ISSUE TITLE
能否增加恢复原版看帖界面的功能 

### ISSUE THREAD

**Issue by W7LL-E** [WiresawBlade/Tieba-Remix#22]
现在的看帖界面感觉太挤了 一个楼层的文字原本是贴近屏幕中心的内容现在被从左到右拉伸的太长 观感上感觉还不如原版
同时新版看帖界面 点击图片的时候还是会先跳转到贴吧原版的看图页面

**Comment by WiresawBlade** [comment]
在设置 `显示 -> 页面布局 -> 最大宽度` 处可以设置容器最大宽度，默认值 1080px 应该不是很宽才对。此外，0.4.1 版本提供页面扩展的开关，具体在 `显示 -> 页面扩展` 。如果没有找到，可以去 release 页面重新下载一次，因为资源更新过。

![image](https://github.com/WiresawBlade/Tieba-Remix/assets/62379610/91dd3da3-1155-4ac8-b0e9-84e0f6849a87)

![image](https://github.com/WiresawBlade/Tieba-Remix/assets/62379610/073c707b-3799-42bd-8162-c9e4e47190d5)

**Comment by WiresawBlade** [comment]
点击帖子里的图片会弹对话框其实是我忘屏蔽了😰，本来就应该弹原版的看图页面的，因为相关功能没做好
