### ISSUE TITLE
不识别tieba.com

### ISSUE THREAD

**Issue by hao1196561270** [WiresawBlade/Tieba-Remix#26]
![图片](https://github.com/WiresawBlade/Tieba-Remix/assets/129362575/e0bb1252-ee15-47e2-8005-b14ac99821fe)
我是启用了这个插件的 请问是什么原因
![图片](https://github.com/WiresawBlade/Tieba-Remix/assets/129362575/a908b119-8819-4266-bb99-3604fdfc773a)

**Comment by WiresawBlade** [comment]
https://tieba.baidu.com 把 末尾的 index.html 删了应该就没事了。上个版本修改了匹配规则，现在还是有点问题

**Comment by WiresawBlade** [comment]
另外，这个脚本目前只对 tampermonkey 有比较好的适配，暴力猴需要等

**Comment by hao1196561270** [comment]
> 另外，这个脚本目前只对 tampermonkey 有比较好的适配，暴力猴需要等

好的了解
