### ISSUE TITLE
关键词屏蔽帖子功能似乎不生效，或者是不能完全屏蔽？

### ISSUE THREAD

**Issue by moiian** [WiresawBlade/Tieba-Remix#27]
已照要求设置为旧版页面。或者是屏蔽词设置有什么格式要求吗

**Comment by WiresawBlade** [comment]
具体是哪个页面、用了哪些屏蔽规则呢，我简单看了下好像没啥问题

**Comment by moiian** [comment]
网站是[剑网3吧](https://tieba.baidu.com/f?kw=%E5%89%91%E7%BD%913&ie=utf-8)
屏蔽规则和未生效的帖子，在截图红框：
![QQ截图20240319193247](https://github.com/WiresawBlade/Tieba-Remix/assets/67492215/849f9cce-b9d6-4eda-91c6-b24f58699daa)

**Comment by WiresawBlade** [comment]
问题已解决，会合并到下一次更新

**Comment by moiian** [comment]
高效，感恩
