### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by xiongaox** [WiresawBlade/Tieba-Remix#3]
希望增加**屏蔽某些水帖**的功能，允许设置永久或者期限

**Comment by WiresawBlade** [comment]
脚本本身就有根据关键词屏蔽贴子的模块，但因缺少ui而难以使用，已在着手改良。
对于设置期限的问题，可以考虑

**Comment by WiresawBlade** [comment]
当前版本已支持对模块添加可直接交互的控件，可以在设置组件直接对屏蔽词进行管理
![20230528150423](https://github.com/WiresawBlade/Tieba-Remix/assets/62379610/2ece53cb-cd43-4db7-b537-f3322c813d6e)
