### ISSUE TITLE
顶栏可以随滚动隐藏吗

### ISSUE THREAD

**Issue by actforjason** [WiresawBlade/Tieba-Remix#37]
贴吧垂直空间很宝贵，顶栏隐藏可以节省空间，类似知乎那样。

**Comment by actforjason** [comment]
自己修改了一下脚本
`#nav-bar[data-v-18e85ac3] {
  position: absolute;`

**Comment by HacksawBlade** [comment]
新版已添加该功能，想达到你要的效果设置为 `顶部固定` 就好了
