### ISSUE TITLE
看帖主页优化

### ISSUE THREAD

**Issue by BeliefDawn** [WiresawBlade/Tieba-Remix#7]
如下图，右栏界面经常空白，并且包含的信息量几近与无，但占据了大量的版面，是否方便增加屏蔽右栏空白的功能
![image](https://github.com/WiresawBlade/Tieba-Remix/assets/43061616/da685178-215e-42b8-ad3e-cd4fb8073b99)

**Comment by WiresawBlade** [comment]
看帖页面已经在做了，对于这个页面的优化也一直是我头疼的地方，因为和其它页面不一样，看帖需要连续且流畅的阅读效果，同时尽量改善空间利用率。我目前会用比较保守折中的布局，因为粗暴地把容器拉长到屏幕宽度的阅读体验其实并不会很好，尤其是对一些超宽屏设备。对于有宽屏需求的人，我会提供一个强制宽屏的开关

**Comment by darkduck9** [comment]
> 看帖页面已经在做了，对于这个页面的优化也一直是我头疼的地方，因为和其它页面不一样，看帖需要连续且流畅的阅读效果，同时尽量改善空间利用率。我目前会用比较保守折中的布局，因为粗暴地把容器拉长到屏幕宽度的阅读体验其实并不会很好，尤其是对一些超宽屏设备。对于有宽屏需求的人，我会提供一个强制宽屏的开关
我觉得空白的地方可以使用用户自己的图片填充，可以提供更换背景图的功能

**Comment by WiresawBlade** [comment]
> > 看帖页面已经在做了，对于这个页面的优化也一直是我头疼的地方，因为和其它页面不一样，看帖需要连续且流畅的阅读效果，同时尽量改善空间利用率。我目前会用比较保守折中的布局，因为粗暴地把容器拉长到屏幕宽度的阅读体验其实并不会很好，尤其是对一些超宽屏设备。对于有宽屏需求的人，我会提供一个强制宽屏的开关
> 
> 我觉得空白的地方可以使用用户自己的图片填充，可以提供更换背景图的功能

可以做，反正也不麻烦
